version: '3.1'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./certs:/etc/nginx/certs
    networks:
      - odoo-dnd-17-v1

networks:
  odoo-dnd-17-v1:
    external: true