# -*- coding: utf-8 -*-
{
    "name": "Algérie | Comptabilité Algérienne",
    "version": "17.1",
    "category": "Accounting/Expenses",
    "author": "Digitaliac",
    "depends": ["base", "account", "sale", "base_accounting_kit", "purchase"],
    "sequence": 1,
    "summary": "Comptabilité Algérienne pour Odoo",
    "author": "DND Consulting",
    "website": "http://www.dndconsulting.com",
    "price": 1299.00,
    "currency": "EUR",
    "support": "contact@dndconsulting.dz",
    "license": "OPL-1",
    "data": [
        "security/ir.model.access.csv",
        "data/reports_data.xml",
        "data/bilan_financier_data.xml",
        "data/tft_financier.xml",
        "data/tcr_financier.xml",
        "data/era.xml",
        "data/tvcp.xml",
        "wizards/generate_end_entry.xml",
        "wizards/bank_reconciliation_views.xml",
        "wizards/compte_resultat.xml",
        "wizards/generate_end_entry.xml",
        "wizards/liasse_fiscal.xml",
        "wizards/compte_resultat.xml",
        "wizards/bilan_report.xml",
        "wizards/livre_tiers.xml",
        "wizards/etat_104.xml",
        "wizards/compte_resultat.xml",
        "wizards/bilan_report.xml",
        "wizards/tft_report.xml",
        "wizards/era_report.xml",
        "wizards/tvcp_report.xml",
        "wizards/amortissement_report.xml",
        "views/exercice.xml",
        "views/account_move_ext.xml",
        "views/g50_views.xml",
        "views/res_company.xml",
        "views/g50_payment_views.xml",
        "views/stock_fluctuation.xml",
        "views/resultat_fiscal.xml",
        "views/affectation_resevere_10_11.xml",
        "views/honoraire_12_13.xml",
        "views/provisions_8_7.xml",
        "views/perte_creance_actions_8_1_8_2.xml",
        "views/amortissement_imobilisation.xml",
        "views/charges_views.xml",
        "views/bilan_config_views.xml",
        "views/compte_resultat_config_views.xml",
        "views/account_report_config.xml",
        "views/bank_releve_views.xml",
        "views/tvcp_lines.xml",
        "reports/dz_accounting_reports.xml",
        "reports/g_50.xml",
        "reports/liasse_fiscal.xml",
        "reports/livre_tier.xml",
        "reports/rapprochement.xml",
        "reports/amortissement.xml",
        "views/kit_accounting.xml",
        "data/timbre_data.xml",
        "views/timbre_view.xml",
        "views/sale_invoice_view.xml",
        "views/fiscal_info.xml",
    ],
    "qweb": [],
    "images": [
        "static/description/Banner.gif",
    ],
    "assets": {
        "web.assets_backend": [
            "dz_accounting/static/src/xml/**/*",
        ],
    },
    "application": True,
}
